name: Slack Pull Request Events
permissions:
  contents: read

on:
  pull_request:
    types: [opened, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted]
  workflow_call:
    inputs:
      slack_channel_id:
        description: 'The Slack channel ID to post notifications to'
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        description: 'Slack Bot token for authentication'
        required: true

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    name: Send Slack PR notifications
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Send Slack notification
        uses: cakarci/pull-request-workflow@fdff04f357a510a7d509f03a33890724a670dfb6 # v1.11.5
        with:
          github-token: ${{ github.token }}
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ inputs.slack_channel_id }}
